-- Woori Farm database restore schema
-- Target: PostgreSQL + PostGIS
-- Mapper coverage:
--   - com.woori.wooribat.mapper.map.FarmlandMapper
--   - com.woori.wooribat.mapper.farm.FarmMapper
--   - com.woori.wooribat.mapper.farm.FarmStatsMapper

CREATE EXTENSION IF NOT EXISTS postgis;

CREATE SCHEMA IF NOT EXISTS farm;

CREATE TABLE IF NOT EXISTS farm.farmland_master (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pnu varchar(32) NOT NULL,
    land_cd varchar(10),
    land_cd_nm varchar(100),
    stdg_cd varchar(20),
    stdg_addr varchar(255),
    fl_ar numeric(14,2),
    cad_con_cn text,
    flight_ymd date,
    updt_ymd timestamp,
    src_sys varchar(50),
    geom geometry(Geometry, 3857) NOT NULL,
    CONSTRAINT ck_farmland_master_area CHECK (fl_ar IS NULL OR fl_ar >= 0)
);

CREATE TABLE IF NOT EXISTS farm.farm_folders (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id varchar(64) NOT NULL,
    name varchar(100) NOT NULL,
    description varchar(500),
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    del_yn char(1) NOT NULL DEFAULT 'N',
    CONSTRAINT ck_farm_folders_del_yn CHECK (del_yn IN ('Y', 'N'))
);

CREATE TABLE IF NOT EXISTS farm.farms (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id varchar(64) NOT NULL,
    folder_id integer NULL REFERENCES farm.farm_folders(id) ON DELETE SET NULL,
    name varchar(100) NOT NULL,
    pnu varchar(32) NOT NULL,
    address varchar(255),
    center_point geometry(Point, 4326),
    area numeric(14,2) NOT NULL,
    current_status varchar(20) NOT NULL DEFAULT '미지정',
    memo text,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    del_yn char(1) NOT NULL DEFAULT 'N',
    farmland_id integer NULL REFERENCES farm.farmland_master(id),
    user_geom geometry(Polygon, 3857),
    source_type varchar(20) NOT NULL DEFAULT 'MASTER',
    CONSTRAINT ck_farms_del_yn CHECK (del_yn IN ('Y', 'N')),
    CONSTRAINT ck_farms_area CHECK (area >= 0),
    CONSTRAINT ck_farms_source_type CHECK (source_type IN ('MASTER', 'USER_DRAWN')),
    CONSTRAINT ck_farms_current_status CHECK (
        current_status IN ('미지정', '씨뿌림', '모내기', '성장중', '수확완료', '휴경')
    ),
    CONSTRAINT ck_farms_source_payload CHECK (
        (source_type = 'MASTER' AND farmland_id IS NOT NULL AND user_geom IS NULL)
        OR
        (source_type = 'USER_DRAWN' AND farmland_id IS NULL AND user_geom IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_farmland_master_geom
    ON farm.farmland_master
    USING gist (geom);

CREATE INDEX IF NOT EXISTS idx_farmland_master_pnu
    ON farm.farmland_master (pnu);

CREATE INDEX IF NOT EXISTS idx_farmland_master_flight_ymd
    ON farm.farmland_master (flight_ymd DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_farm_folders_user_active
    ON farm.farm_folders (user_id, created_at DESC)
    WHERE del_yn = 'N';

CREATE INDEX IF NOT EXISTS idx_farms_user_active
    ON farm.farms (user_id, created_at DESC)
    WHERE del_yn = 'N';

CREATE INDEX IF NOT EXISTS idx_farms_folder_active
    ON farm.farms (folder_id, created_at DESC)
    WHERE del_yn = 'N';

CREATE INDEX IF NOT EXISTS idx_farms_farmland_id
    ON farm.farms (farmland_id);

CREATE INDEX IF NOT EXISTS idx_farms_center_point
    ON farm.farms
    USING gist (center_point);

CREATE INDEX IF NOT EXISTS idx_farms_user_geom
    ON farm.farms
    USING gist (user_geom);

CREATE OR REPLACE FUNCTION farm.fn_touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION farm.fn_sync_farm_fields()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_master farm.farmland_master%ROWTYPE;
BEGIN
    NEW.created_at := COALESCE(NEW.created_at, CURRENT_TIMESTAMP);
    NEW.updated_at := CURRENT_TIMESTAMP;
    NEW.del_yn := COALESCE(NEW.del_yn, 'N');
    NEW.source_type := COALESCE(
        NULLIF(NEW.source_type, ''),
        CASE
            WHEN NEW.user_geom IS NOT NULL THEN 'USER_DRAWN'
            ELSE 'MASTER'
        END
    );
    NEW.current_status := COALESCE(NULLIF(NEW.current_status, ''), '미지정');

    IF NEW.source_type = 'MASTER' THEN
        IF NEW.farmland_id IS NULL THEN
            RAISE EXCEPTION 'farmland_id is required when source_type = MASTER';
        END IF;

        SELECT *
          INTO v_master
          FROM farm.farmland_master
         WHERE id = NEW.farmland_id;

        IF NOT FOUND THEN
            RAISE EXCEPTION 'farmland_master row not found: id=%', NEW.farmland_id;
        END IF;

        NEW.pnu := COALESCE(NULLIF(NEW.pnu, ''), v_master.pnu);
        NEW.address := COALESCE(NULLIF(NEW.address, ''), v_master.stdg_addr);
        NEW.area := COALESCE(
            NEW.area,
            v_master.fl_ar,
            ROUND(CAST(ST_Area(ST_Transform(v_master.geom, 5179)) AS numeric), 2)
        );
        NEW.center_point := ST_Transform(ST_Centroid(v_master.geom), 4326);
        NEW.user_geom := NULL;
    ELSIF NEW.source_type = 'USER_DRAWN' THEN
        IF NEW.user_geom IS NULL THEN
            RAISE EXCEPTION 'user_geom is required when source_type = USER_DRAWN';
        END IF;

        NEW.farmland_id := NULL;
        NEW.pnu := COALESCE(NULLIF(NEW.pnu, ''), 'USER_DRAWN');
        NEW.area := COALESCE(
            NEW.area,
            ROUND(CAST(ST_Area(ST_Transform(NEW.user_geom, 5179)) AS numeric), 2)
        );
        NEW.center_point := ST_Transform(ST_Centroid(NEW.user_geom), 4326);
    ELSE
        RAISE EXCEPTION 'unsupported source_type: %', NEW.source_type;
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION farm.fn_unassign_farms_on_folder_soft_delete()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.del_yn = 'Y' AND COALESCE(OLD.del_yn, 'N') <> 'Y' THEN
        UPDATE farm.farms
           SET folder_id = NULL,
               updated_at = CURRENT_TIMESTAMP
         WHERE folder_id = NEW.id
           AND COALESCE(del_yn, 'N') = 'N';
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_farm_folders_touch_updated_at ON farm.farm_folders;
CREATE TRIGGER trg_farm_folders_touch_updated_at
BEFORE UPDATE ON farm.farm_folders
FOR EACH ROW
EXECUTE FUNCTION farm.fn_touch_updated_at();

DROP TRIGGER IF EXISTS trg_farms_sync_fields ON farm.farms;
CREATE TRIGGER trg_farms_sync_fields
BEFORE INSERT OR UPDATE ON farm.farms
FOR EACH ROW
EXECUTE FUNCTION farm.fn_sync_farm_fields();

DROP TRIGGER IF EXISTS trg_farm_folders_soft_delete ON farm.farm_folders;
CREATE TRIGGER trg_farm_folders_soft_delete
AFTER UPDATE OF del_yn ON farm.farm_folders
FOR EACH ROW
EXECUTE FUNCTION farm.fn_unassign_farms_on_folder_soft_delete();

COMMENT ON SCHEMA farm IS 'Woori Farm application schema.';
COMMENT ON TABLE farm.farmland_master IS '농지 원본 마스터. 지도 클릭 조회와 MASTER 농지 등록에 사용.';
COMMENT ON TABLE farm.farm_folders IS '사용자별 농지 분류 폴더.';
COMMENT ON TABLE farm.farms IS '사용자 저장 농지. 원본 농지(MASTER)와 직접 그린 농지(USER_DRAWN)를 함께 관리.';
COMMENT ON COLUMN farm.farms.user_id IS '구글 로그인 user id(sub) 문자열을 그대로 저장.';
COMMENT ON COLUMN farm.farms.center_point IS '지도 이동용 중심점. EPSG:4326.';
COMMENT ON COLUMN farm.farms.user_geom IS '사용자가 직접 그린 폴리곤. EPSG:3857.';
COMMENT ON COLUMN farm.farms.source_type IS 'MASTER 또는 USER_DRAWN.';
